/**
 *     USER
 */
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
// Admin Control Panel
export const GET_USERS_LIST_SUCCESS = "GET_USERS_LIST_SUCCESS";
export const GET_USERS_LIST_FAIL = "GET_USERS_LIST_FAIL";
export const GET_USER_DETAILS_SUCCESS = "GET_USERS_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAIL = "GET_USER_DETAILS_FAIL";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
export const DELETE_USERS_FAIL = "DELETE_USERS_FAIL";
export const UPDATE_USERS_SUCCESS = "UPDATE_USERS_SUCCESS";
export const UPDATE_USERS_FAIL = "UPDATE_USERS_FAIL";
export const USER_LIST_LOADING = "USER_EDIT_LOADING";
export const USER_DETAILS_LOADING = "USER_DETAILS_LOADING";
/**
 *     PRODUCT
 */
// Product List
export const PRODUCT_LIST_LOADING = "PRODUCT_LIST_LOADING";
export const PRODUCT_LIST_LOADED = "PRODUCT_LIST_LOADED";
export const PRODUCT_LIST_CREATE_SUCCESS = "PRODUCT_LIST_CREATE_SUCCESS";
export const PRODUCT_LIST_CREATE_FAIL = "PRODUCT_LIST_CREATE_FAIL";
export const PRODUCT_LIST_GET_SUCCESS = "PRODUCT_LIST_GET_SUCCESS";
export const PRODUCT_LIST_GET_FAIL = "PRODUCT_LIST_GET_FAIL";
// Product Details
export const PRODUCT_DETAILS_LOADING = "PRODUCT_DETAILS_LOADING";
export const PRODUCT_DETAILS_GET_SUCCESS = "PRODUCT_DETAILS_GET_SUCCESS";
export const PRODUCT_DETAILS_GET_FAIL = "PRODUCT_DETAILS_GET_FAIL";
// Product Edit
export const PRODUCT_EDIT_LOADING = "PRODUCT_EDIT_LOADING";
export const PRODUCT_EDIT_DELETE_SUCCESS = "PRODUCT_EDIT_DELETE_SUCCESS";
export const PRODUCT_EDIT_UDPATE_SUCCESS = "PRODUCT_EDIT_UDPATE_SUCCESS";
export const PRODUCT_EDIT_DELETE_FAIL = "PRODUCT_EDIT_DELETE_FAIL";
export const PRODUCT_EDIT_UDPATE_FAIL = "PRODUCT_EDIT_UDPATE_FAIL";

/**
 *     CART
 */
export const CART_LOADING = "CART_LOADING";
export const CART_GET_SUCCESS = "CART_GET_SUCCESS";
export const CART_GET_FAIL = "CART_GET_FAIL";
export const CART_ADD_SUCCESS = "CART_ADD_SUCCESS";
export const CART_ADD_FAIL = "CART_ADD_FAIL";
export const CART_REMOVE_FAIL = "CART_REMOVE_FAIL";
export const CART_REMOVE_SUCCESS = "CART_REMOVE_SUCCESS";
export const CART_BUY_SUCCESS = "CART_BUY_SUCCESS";
export const CART_BUY_FAIL = "CART_BUY_FAIL";
export const CART_UPDATE_SUCCESS = "CART_UPDATE_SUCCESS";
export const CART_UPDATE_FAIL = "CART_UPDATE_FAIL";
export const CART_CLEAR = "CART_CLEAR";
/**
 *      History
 */
export const HISTORY_LOADING = "HISTORY_LOADING";
export const HISTORY_GET_SUCCESS = "HISTORY_GET_SUCCESS";
export const HISTORY_GET_FAIL = "HISTORY_GET_FAIL";
export const HISTORY_CLEAR = "HISTORY_CLEAR";
/**
 *     ERROR
 */
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

/**
 *     ROLE
 */
export const ROLE_GUEST = "GUSET";
export const ROLE_ADMIN = "ADMIN";
export const ROLE_USER = "USER";
