exports.MISSING_NAME = "MISSING_NAME";
exports.MISSING_EMAIL = "MISSING_EMAIL";
exports.MISSING_PASSWORD = "MISSING_PASSWORD";
exports.EMAIL_EXIST = "EMAIL_EXIST";
exports.INVALID_PASSWORD = "INVALID_PASSWORD";
exports.USER_NOT_FOUND = "USER_NOT_FOUND";
exports.TOKEN_NOT_MATCH = "TOKEN_NOT_MATCH";
exports.TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND";
