/**
 *  Auth
 */

exports.PASSWORD_INVALID = "PASSWORD_INVALID";
exports.USER_NOT_FOUND = "USER_NOT_FOUND";
exports.TOKEN_NOT_MATCH = "TOKEN_NOT_MATCH";
exports.TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND";

exports.EMAIL_MISSING = "EMAIL_MISSING";
exports.EMAIL_EXIST = "EMAIL_EXIST";
exports.EMAIL_FORMAT = "EMAIL_FORMAT";

exports.NAME_MISSING = "NAME_MISSING";
exports.NAME_FORMAT = "NAME_FORMAT";

exports.PASSWORD_MISSING = "PASSWORD_MISSING";
exports.PASSWORD_FORMAT = "PASSWORD_FORMAT";

exports.LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
